version: 2.1

# orbs to use in steps
orbs:
  aws-cli: circleci/aws-cli@1.2.1

# define jobs we want to run in pipeline
jobs:
  build:
    docker:
      - image: circleci/node:latest
    parallelism: 1
    working_directory: ~/react-application
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-application
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths: build
  deploy:
    executor: aws-cli/default
    working_directory: ~/react-application
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-application
      - aws-cli/setup:
        profile-name: default
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync ./dist/ s3://nickholvast.com --delete

# orchestrate job run sequence
workflows:
  build-and-deploy:
    jobs:
      - build
          # filters:
          #   branches:
          #     only:
          #       - infrastructure
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - infrastructure
